server:
  port: 8081

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center_one?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Sillyforce,
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always