spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://101.201.142.75:3306/content_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc.123
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 101.201.142.75:8848
#        namespace: a2b425a7-92b5-494a-941f-bbfab80e9959

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    clients: user-center
    enabled: true


# feign配置日志
logging:
  level:
    com.soft1851.contentcenter.feignclient.UserCenterFeignClient: debug

#feign:
#  client:
#    config:
#      user-center:
#        loggerLevel: full