spring:
  application:
    name: content-center
#  zipkin:
#    base-url: http://localhost:9411/
#    discoveryClientEnabled: false
#  sleuth:
#    sampler:
#      # 抽样率，默认是0.1（10%）
#      probability: 1.0
  datasource:
    url: jdbc:mysql://101.201.142.75:3306/content_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc.123
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
#        server-addr: 101.201.142.75:8848
         server-addr: localhost:8848
#        namespace: a2b425a7-92b5-494a-941f-bbfab80e9959

    sentinel:
      transport:
        #指定sentinel控制台地址
        dashboard: localhost:8080
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    clients: user-center
    enabled: true


# feign配置日志
logging:
  level:
    com.soft1851.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.soft1851.contentcenter.feignclient.interceptor.TokenInterceptor
  httpclient:
    enable: true
    max-connections: 200
    max-connections-per-route: 50

rocketmq:
  name-server: 101.201.142.75:9876
  producer:
    # 必须指定group
    group: test-group